[versions]
agp = "8.13.2"
kotlin = "2.4.0"
compose-bom = "2025.10.01"
activity = "1.11.0"
coroutines = "1.10.2"
gson = "2.13.2"
litertlm = "0.17.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
mlkit-text = { module = "com.google.mlkit:text-recognition", version = "16.0.1" }
mlkit-labeling = { module = "com.google.mlkit:image-labeling", version = "17.0.9" }
mlkit-face = { module = "com.google.mlkit:face-detection", version = "16.1.7" }
mlkit-segmentation = { module = "com.google.mlkit:segmentation-selfie", version = "16.0.0-beta6" }
coil-compose = { module = "io.coil-kt:coil-compose", version = "2.7.0" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
litertlm-android = { module = "com.google.ai.edge.litertlm:litertlm-android", version.ref = "litertlm" }
junit = { module = "junit:junit", version = "4.13.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
